server.name: "petfamily-kibana"
server.host: "0.0.0.0"
server.port: 5601

elasticsearch.hosts: ["http://elasticsearch:9200"]

telemetry.enabled: false
telemetry.optIn: false

xpack.security.enabled: false

logging:
  appenders:
    default:
      type: console
      layout:
        type: pattern
  root:
    appenders: [default]
    level: info
